### ISSUE TITLE
NaN FPP for Kepler target

### ISSUE THREAD

**Issue by martindevora** [stevengiacalone/triceratops#10]
Hi, I was trying the same Kepler target from the official example (using v1.0.9) but with a different processed light curve and apertures. I'm attaching the compressed example. I'm binning the curve with 100 bins only so it should not be the problem right now. FPP is NaN and many scenarios lack of probability.

[example_kepler.zip](https://github.com/stevengiacalone/triceratops/files/6937825/example_kepler.zip)

In addition, I was looking into the code and wanted to understand the change you made in this line (Line 140) from marginal_likelihood:
`Z = np.mean(np.exp(lnL + lnprior_Mstar + lnprior_Porb + 709))`

What does the `709` value mean?

Kind regards.

**Comment by martindevora** [comment]
The same is happening for a TESS target. For this case, downgrading to 1.0.8 works instead, so it'd seem something changed in the triceratops logic also for TESS targets.

**Comment by stevengiacalone** [comment]
Oops, this is due to a bug I introduced in the last update. It should work now (after updating to version 1.0.10).

**Comment by stevengiacalone** [comment]
Also, to answer your question above about "709." Python's floating point precision is limited to ~ [e^-709, e^709]. Any positive number below that range will be returned as 0 and any positive number above that range will be inf. In some cases - especially cases where there are a lot of data points being entered into the calculation - the log likelihoods from the light curve simulations would fall below this range. As a result, the line above would return a marginalized probability (Z in the line you provided) of 0 for the scenario. This was why you were getting FPP=nan when you didn't bin your data before.

Introducing the "+709" was a quick fix for this. It's an offset that is applied uniformly across scenarios, so that it doesn't affect the final FPP, that allows the log likelihoods to be smaller.

**Comment by martindevora** [comment]
Well it seems that the issue is fixed now. 

Thanks for your fix!
