### ISSUE TITLE
Clarify on the nearby stars included in analysis 

### ISSUE THREAD

**Issue by orionlee** [stevengiacalone/triceratops#21]
This is a question and a feature suggestion regarding nearby stars included in analysis

**Question:** For nearby stars with missing stellar parameters (mass, rad, or Teff), are they include in analysis?

![image](https://user-images.githubusercontent.com/250644/215240440-04048177-0498-4904-bfa4-b30e7a42f811.png)

If they are excluded, it might be helpful to issue a warning.

---

**Suggestion:** in the [paper](https://iopscience.iop.org/article/10.3847/1538-3881/abc6af#ajabc6afs2), it is suggested that stars with little contribution to the aperture are excluded using a relative transit depth measure.

It might be helpful to include the relative transit depth measure in `target.stars`, so that users can easily identify nearby stars included in the analysis.

Currently, I am doing something like this:
```python
# stars with δs >= 1 are excluded from further analysis (section 2.1 of the paper)
target.stars["rel_tdepth"] = tdepth / target.stars["fluxratio"]

target.stars[target.stars["rel_tdepth"] < 1]  # show stars still included in the analysis
```

**Comment by stevengiacalone** [comment]
Nearby stars will never be dropped from the analysis automatically. Missing masses, radii, and Teffs are assigned Solar values if none are listed in the TIC. The user is notified when this happens when they run `.calc_probs()`. This is obviously not a great approximation, but it's better than omitting them from the analysis altogether. One can also manually assign values in the `.stars` dataframe using the results of an SED or isochrone fit, but this is left to the user.

The value "tdepth" in the `.stars` dataframe _is_ the relative transit depth. Specifically, it is the depth that the nearby star would need to have to produce the transit, given the amount of flux that star is contributing the the chosen aperture. Nearby stars that would need tdepth > 1 to explain the signal are already excluded from the analysis, so no additional calculations are needed.

**Comment by orionlee** [comment]
Somehow I failed to notice the warnings issued in `.calc_probs()` for using solar values initially, but it's there when I looked at the output again.

For relative transit depth, thanks for the clarification. It could be helpful to explain it in the `example.ipynb` .
